apiVersion: v1
items:
- apiVersion: v1
  kind: LimitRange
  metadata:
    creationTimestamp: null
    name: test-docker-core-resource-limits
  spec:
    limits:
    - default:
        cpu: 500m
        memory: 1536Mi
      defaultRequest:
        cpu: 50m
        memory: 256Mi
      max:
        memory: 6Gi
      min:
        memory: 10Mi
      type: Container
    - max:
        memory: 12Gi
      min:
        memory: 6Mi
      type: Pod
kind: List
metadata: {}
