apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: builder
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: default
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: deployer
kind: List
metadata: {}
